//
//  UITableView+NightVersion.h
//  UITableView+NightVersion
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and
//  test it. And finally open a pull request.

#import <UIKit/UIKit.h>
#import "UITableView+BackgroundColor.h"
#import "UITableView+SeparatorColor.h"


@interface UITableView (NightVersion)

/**
 * Change UITableView color according to the current theme version
 */
- (void)changeColor;

/**
 * Change UITableView color according to the current theme version with animation
 *
 * @param duration animation duration
 */
- (void)changeColorWithDuration:(CGFloat)duration;

@end
